# -*- mode: ruby -*-
# vi: set ft=ruby :

# This requires Vagrant 1.6.2 or newer (earlier versions can't reliably
# configure the Fedora 20 network stack).
Vagrant.require_version ">= 1.6.2"

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

ENV['VAGRANT_DEFAULT_PROVIDER'] = 'virtualbox'

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "centos65-x86_64-20140116" # https://github.com/2creatives/vagrant-centos/releases/download/v6.5.3/centos65-x86_64-20140116.box
  #config.vm.provision :shell, :path => "bootstrap.py", :privileged => true,
  #    :args => [
  #        ENV.fetch('FLOCKER_RPM_VERSION', ''),
  #        ENV.fetch('FLOCKER_BRANCH', ''),
  #        ENV.fetch('FLOCKER_BUILD_SERVER', '')
  #    ]
  # Prepare caches
  #config.vm.provision :shell, :path => "cache.sh", :privileged => true
  # Cleanup
  #config.vm.provision :shell, :path => "cleanup.sh", :privileged => true
  config.ssh.private_key_path = "~/.vagrant.d/insecure_private_key"

  if Vagrant.has_plugin?("vagrant-cachier")
    config.cache.scope = :box
  end

  config.vm.define "node1" do |node1|
    node1.vm.network :private_network, :ip => "172.16.255.250"
    node1.vm.hostname = "node1"
  end

  config.vm.define "node2" do |node2|
    node2.vm.network :private_network, :ip => "172.16.255.251"
    node2.vm.hostname = "node2"
  end

end
