# -*- mode: ruby -*-
# vi: set ft=ruby :

# This requires Vagrant 1.6.2 or newer (earlier versions can't reliably
# configure the Fedora 20 network stack).
Vagrant.require_version ">= 1.6.2"

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

ENV['VAGRANT_DEFAULT_PROVIDER'] = 'virtualbox'

FLOCKER_VM=ARGV[1]
SHEPERD_VM="sheperd"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

  config.vm.provision "shell", path: "centos/cloud-centos-7.sh"
  #config.vm.provision "shell", path: "docker-bootstrap.sh" # start etcd

  config.vm.box = "chef/centos-7.0"
  config.vm.box_version = "= 1.0.0"

  config.vm.define FLOCKER_VM do |flocker_node|
    flocker_node.vm.hostname = FLOCKER_VM
    flocker_node.vm.network "private_network", type: "dhcp"
  end
  config.vm.define SHEPERD_VM do |sheperd|
    sheperd.vm.hostname = SHEPERD_VM
    sheperd.vm.network "private_network", type: "dhcp"
  end

end
